name: CI for bazel-utils
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Build all targets 
        run: bazel build //...
      - name: Test all targets
        run: bazel test //...